name: CodeCov Upload

on:
  pull_request:

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Unit Tests with Coverage
        run: |
          pytest --cov=app --cov-report=xml:unit_coverage.xml --cov-fail-under=76 tests/unit/
      - name: Upload Unit Test Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./unit_coverage.xml
          flags: unit_tests
          token: ${{ secrets.CODECOV_TOKEN }}

  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Integration Tests with Coverage
        run: |
          pytest --cov=app --cov-report=xml:integration_coverage.xml --cov-fail-under=76 tests/integration/
      - name: Upload Integration Test Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./integration_coverage.xml
          flags: integration_tests
          token: ${{ secrets.CODECOV_TOKEN }}
